### INDEX Users
GET http://localhost:3000/users.json

### SHOW Users
GET http://localhost:3000/users/5.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTM5MzUzOTR9.pjny7iQcCBwOHqWA77cpAnU5DxIaavZKvcP3PsAcd5Y

### CREATE Users (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Michele",
  "email_address": "michele2@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### UPDATE Users (change password or change/join organization)
PATCH http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTM5MzUzOTR9.pjny7iQcCBwOHqWA77cpAnU5DxIaavZKvcP3PsAcd5Y
Content-Type: application/json

{
  "organization_id": 
}

### CREATE Sessions (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email_address": "ta@email.com",
  "password": "password"
}

### INDEX Organizations
GET http://localhost:3000/organizations.json

### SHOW Organizations
GET http://localhost:3000/organizations/55.json

### CREATE Organizations
POST http://localhost:3000/organizations.json
Content-Type: application/json

{
  "name": "Bob's Burgers",
  "hourly_rate": 23
}

### UPDATE Organizations
PATCH http://localhost:3000/organizations/1.json
Content-Type: application/json

{
  "name": "Bob's Burgers",
  "hourly_rate": 24
}

### DESTROY Organizations
DELETE http://localhost:3000/organizations/57.json

### INDEX Shifts
GET http://localhost:3000/shifts.json
Content-Type: application/json

### CREATE Shifts
POST http://localhost:3000/shifts.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTM5MzUzOTR9.pjny7iQcCBwOHqWA77cpAnU5DxIaavZKvcP3PsAcd5Y
Content-Type: application/json

{
  "user_id": 7,
  "start": "2022-03-31 06:45:00",
  "finish": "2022-03-31 15:15:00",
  "break_length": 30
}

### DESTROY Shifts
DELETE http://localhost:3000/shifts.json
Content-Type: application/json
# YYYY-MM-DD HH:MM:SS